FROM python:3.13-slim
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app


CMD ["fastapi", "dev", "app/main.py","--host", "0.0.0.0", "--port", "80"]
# CMD ["fastapi", "run", "app/main.py", "--host", "0.0.0.0", "--port", "10000"]