"""add username and admin fields to user

Revision ID: 48fae4cc5873
Revises: 6ffe31f36e4c
Create Date: 2026-04-13 19:55:12.558157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "48fae4cc5873"
down_revision: Union[str, Sequence[str], None] = "6ffe31f36e4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_column("user", "is_active")
    op.drop_column("user", "is_admin")
    op.drop_column("user", "username")
    # ### end Alembic commands ###
