"""User change city for flag#

Revision ID: 6d10b9ff8ab4
Revises: ec002c0a86da
Create Date: 2026-05-05 20:55:45.118272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d10b9ff8ab4'
down_revision: Union[str, Sequence[str], None] = 'ec002c0a86da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('flag', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'flag')
    # ### end Alembic commands ###
