"""initial_schema_final

Revision ID: 7dd86b27ca49
Revises:
Create Date: 2026-04-10 12:48:12.740921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7dd86b27ca49"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brand_name"), "brand", ["name"], unique=True)
    op.create_table(
        "model",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brand.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_name"), "model", ["name"], unique=False)
    op.create_table(
        "version",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("engine", sa.Float(), nullable=True),
        sa.Column("bhp", sa.Float(), nullable=True),
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_version_bhp"), "version", ["bhp"], unique=False)
    op.create_index(op.f("ix_version_engine"), "version", ["engine"], unique=False)
    op.create_index(op.f("ix_version_name"), "version", ["name"], unique=False)
    op.create_index(op.f("ix_version_year"), "version", ["year"], unique=False)
    op.create_table(
        "disc",
        sa.Column("position", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("holes", sa.Integer(), nullable=True),
        sa.Column("style", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("diameter", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("thickness", sa.Float(), nullable=True),
        sa.Column("center_bore", sa.Float(), nullable=True),
        sa.Column("pcd", sa.Float(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_disc_center_bore"), "disc", ["center_bore"], unique=False)
    op.create_index(op.f("ix_disc_diameter"), "disc", ["diameter"], unique=False)
    op.create_index(op.f("ix_disc_height"), "disc", ["height"], unique=False)
    op.create_index(op.f("ix_disc_holes"), "disc", ["holes"], unique=False)
    op.create_index(op.f("ix_disc_pcd"), "disc", ["pcd"], unique=False)
    op.create_index(op.f("ix_disc_position"), "disc", ["position"], unique=False)
    op.create_index(op.f("ix_disc_style"), "disc", ["style"], unique=False)
    op.create_index(op.f("ix_disc_thickness"), "disc", ["thickness"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_disc_thickness"), table_name="disc")
    op.drop_index(op.f("ix_disc_style"), table_name="disc")
    op.drop_index(op.f("ix_disc_position"), table_name="disc")
    op.drop_index(op.f("ix_disc_pcd"), table_name="disc")
    op.drop_index(op.f("ix_disc_holes"), table_name="disc")
    op.drop_index(op.f("ix_disc_height"), table_name="disc")
    op.drop_index(op.f("ix_disc_diameter"), table_name="disc")
    op.drop_index(op.f("ix_disc_center_bore"), table_name="disc")
    op.drop_table("disc")
    op.drop_index(op.f("ix_version_year"), table_name="version")
    op.drop_index(op.f("ix_version_name"), table_name="version")
    op.drop_index(op.f("ix_version_engine"), table_name="version")
    op.drop_index(op.f("ix_version_bhp"), table_name="version")
    op.drop_table("version")
    op.drop_index(op.f("ix_model_name"), table_name="model")
    op.drop_table("model")
    op.drop_index(op.f("ix_brand_name"), table_name="brand")
    op.drop_table("brand")
    # ### end Alembic commands ###
