"""create post table and added backpopulates to Version and User

Revision ID: 8a803973cdbf
Revises: 48fae4cc5873
Create Date: 2026-04-17 12:45:46.432548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8a803973cdbf"
down_revision: Union[str, Sequence[str], None] = "48fae4cc5873"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["version_id"], ["version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_post_date"), "post", ["date"], unique=False)
    op.create_index(op.f("ix_post_user_id"), "post", ["user_id"], unique=False)
    op.create_index(op.f("ix_post_version_id"), "post", ["version_id"], unique=False)
    # op.drop_index(op.f("username"), table_name="user")
    # op.drop_index(op.f("username_2"), table_name="user")
    # op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index(op.f("username_2"), "user", ["username"], unique=True)
    op.create_index(op.f("username"), "user", ["username"], unique=True)
    op.drop_index(op.f("ix_post_version_id"), table_name="post")
    op.drop_index(op.f("ix_post_user_id"), table_name="post")
    op.drop_index(op.f("ix_post_date"), table_name="post")
    op.drop_table("post")
    # ### end Alembic commands ###
