"""Added new fields to User in database#

Revision ID: ec002c0a86da
Revises: 8006baf72f34
Create Date: 2026-04-29 20:36:41.856737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec002c0a86da'
down_revision: Union[str, Sequence[str], None] = '8006baf72f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('fav_circuit', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('fav_pads', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('url_avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'url_avatar')
    op.drop_column('user', 'fav_pads')
    op.drop_column('user', 'fav_circuit')
    op.drop_column('user', 'city')
    op.drop_column('user', 'country')
    # ### end Alembic commands ###
