name: Keep Render API Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: |
          curl -v -f -X GET "https://needtobrakeapp.onrender.com/git-with-db" \
          -H "User-Agent: GitHubAction-Pinger"
